### ISSUE TITLE
Authentication failure while having the auth_token

### ISSUE THREAD

**Issue by Extraltodeus** [Eigenbahn/cadavre-exquis-dungeon#1]
If I do a print of ai_list[0].get_auth_token() at line 68 I am able to see my auth token.

Yet I get this error : 

```
Traceback (most recent call last):
  File "cadavre_exquis_dungeon/__init__.py", line 130, in <module>
    main()
  File "cadavre_exquis_dungeon/__init__.py", line 89, in main
    ai.api._create_adventure(ai.api.scenario_id)
  File "/usr/lib/python3.8/site-packages/ai_dungeon_cli/impl/api/client.py", line 226, in _create_adventure
    result = self._execute_query('''
  File "/usr/lib/python3.8/site-packages/ai_dungeon_cli/impl/api/client.py", line 39, in _execute_query
    return self.gql_client.execute(gql(query), variable_values=params)
  File "/usr/lib/python3.8/site-packages/gql/client.py", line 120, in execute
    data: Dict[Any, Any] = loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/gql/client.py", line 99, in execute_async
    return await session.execute(document, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/gql/client.py", line 342, in execute
    raise TransportQueryError(str(result.errors[0]), errors=result.errors)
gql.transport.exceptions.TransportQueryError: {'message': 'Not authorized.', 'locations': [{'line': 2, 'column': 3}], 'path': ['createAdventureFromScenarioId'], 'extensions': {'code': 'UNAUTHENTICATED'}}
```

Note : I don't run it with anaconda as I am on ArchLinux and it is not an officially supported package.

ai-dungeon-cli works perfectly when I use it from my CLI.

**Comment by Extraltodeus** [comment]
Not sure that this is the best way to do so but changing the lines 70-77 to below's code did the trick :

```
        auth_token = ai_list[0].get_auth_token()
        if not auth_token:
            ai_list[0].login()
            auth_token = ai_list[0].api.access_token

        for i in range(1, nb_ia):
            ai_list[i].api.access_token = auth_token
            ai_list[i].api.update_session_access_token(auth_token)
```

**Comment by Extraltodeus** [comment]
Wrong manipulation with the closing issue button. Sorry.

**Comment by p3r7** [comment]
Ah, yes indeed, my bad.

`AiDungeonApi.update_session_access_token()` needs to be called systematically to register the auth token to the websocket/gql session.

https://github.com/Eigenbahn/cadavre-exquis-dungeon/commit/3ab318568f253767e10f84fae1e435b521b182ed should fix it.
